---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{service.name}}-storage-claim"
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G