---
apiVersion: v1
kind: Service
metadata:
  name: {{service.name}}
spec:
  type: LoadBalancer
  selector:
    app: {{service.name}}
  ports:
    - port: {{service.port}}
      targetPort: {{service.targetPort}}